remote_theme: just-the-docs/just-the-docs

title: AWS Testing
url: "https://aws-testing.ideapool.community" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

exclude:
 # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
 # specific to the theme website:
   - bin/
   - lib/
   - "*.gemspec"
   - "*.gem"
   - LICENSE
   - package.json
   - package-lock.json
   - Rakefile
   - README.md

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  more:
    title: More information
    color: grey-lt
    
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022- Idea Pool Community. Distributed by an <a href=\"https://github.com/idea-pool/aws-testing/tree/main/LICENSE\">MIT license.</a> This site is <strong>under development</strong>."

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# logo: "/assets/images/idea-pool.png"

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

mermaid:
  version: "9.1.6"

heading_anchors: true

aux_links:
  "@GitHub":
    - "//github.com/idea-pool"
  "@WeAreCommunity":
    - "//ideapool.community"

aux_links_new_tab: true

# nav_external_links:
#   - title: Idea Pool@GitHub
#     url: https://github.com/idea-pool
#   - title: Idea Pool@WeAreCommunity
#     url: http://ideapool.community

gh_edit_link: true
gh_edit_link_text: Help us improve this page
gh_edit_repository: https://github.com/Idea-Pool/aws-testing

ga_tracking: GTM-MN2TZZV
ga_tracking_anonymize_ip: true